### ISSUE TITLE
App crashes when JWT token expired before it retried to refresh it on init

### ISSUE THREAD

**Issue by buuuudzik** [Iterable/react-native-sdk#565]
We're using Iterable SDK in our project in the latest version:
`"@iterable/react-native-sdk": "1.3.19",`

Recently we've found such errors on the production and I've reproduced this in dev mode. And it looks that when the app was in logged in state and then fully closed for the longer time than JWT token expiration time then Iterable SDK doesn't try to refresh it before it try to use it. It causes the full app crash and we can't do nothing to block this.

Can you make it impossible that your SDK can fully crash the app? There should be an error handler which would give the way to check what has happened in SDK but without the low level error which cannot be handled.

It could be helpful if we could both pass the new auth token in `Iterable.setEmail(email, token)` and still use auto refreshing mechanism which isn't possible now and when we will pass the token in the mentioned method auto-refreshing mechanism stop to work.

Error found in our app which fully crashes the app:
![CleanShot 2024-07-25 at 15 57 19](https://github.com/user-attachments/assets/bacc28cc-e42b-4c6c-99a1-916946a2e2ae)

**Comment by jena-chakour** [comment]
Hi @buuuudzik, thanks for sharing -- I've reached out through your Support ticket for additional details; please share the full crash log and device info. We will look into this :)

**Comment by buuuudzik** [comment]
Below you can find the whole crashlog from BugSnag from the production:
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)

Caused by: java.lang.AbstractMethodError: abstract method "void com.iterable.iterableapi.IterableAuthHandler.onAuthFailure(com.iterable.iterableapi.AuthFailure)"
        at com.iterable.iterableapi.IterableAuthManager.handleAuthFailure(IterableAuthManager.java:176)
        at com.iterable.iterableapi.IterableRequestTask.executeApiRequest(IterableRequestTask.java:193)
        at com.iterable.iterableapi.IterableRequestTask.doInBackground(IterableRequestTask.java:61)
        at com.iterable.iterableapi.IterableRequestTask.doInBackground(IterableRequestTask.java:34)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
```

**Comment by buuuudzik** [comment]
If it's about a device, it can be reproduced on every Android phone, we detected it also on OS version from Android 10 to 14. Personally I'm using for tests Samsung Note 10 Plus.

**Comment by buuuudzik** [comment]
In our case it looks that this helps (no crash and lib can continue fetching new JWT token and sending events):
![CleanShot 2024-07-27 at 08 18 58@2x](https://github.com/user-attachments/assets/f7724fa9-a561-4fc2-bba9-73a835df9072)

**Comment by buuuudzik** [comment]
Maybe it's related with this issue:
https://github.com/Iterable/iterable-android-sdk/issues/741

**Comment by lposen** [comment]
Hi all.  Can you confirm whether or not this is still an issue?

**Comment by lposen** [comment]
@buuuudzik Have you patched the Iterable RN SDK with a newer version of the Android SDK, by any chance?

The Iterable RN SDK hasn't incorporated newer versions of the Iterable Android SDK, so there will likely be several breaking issues if you have patched it with a newer version.  The way that token refreshes are handled changed quite substantially in the newer versions of the Iterable Android SDK. 

We are currently working on bringing the RN SDK up to speed with the newer Android and iOS versions.

**Comment by buuuudzik** [comment]
Thanks @lposen

**Comment by lposen** [comment]
Hi @buuuudzik  -- JWT functionality has been released as of version 2.2.0.  Let me know if you have any questions.
